$:.unshift 'lib'

require 'active_mailbox/version'

Gem::Specification.new do |s|
  s.name             = 'active_mailbox'
  s.version          = ActiveMailbox::Version
  s.date             = Time.now.strftime('%Y-%m-%d')
  s.summary          = 'ActiveMailbox: API/CLI for Asterisk Voicemail'
  s.homepage         = "http://github.com/itspriddle/active_mailbox"
  s.authors          = ['Joshua Priddle']
  s.email            = 'jpriddle@nevercraft.net'

  s.files            = %w[ Rakefile README.markdown LICENSE ]
  s.files           += Dir['bin/**/*']
  s.files           += Dir['lib/**/*']
  s.files           += Dir['test/**/*']

  s.add_development_dependency('shoulda', '= 2.11.3')
  s.add_development_dependency('turn',    '= 0.8.1')

  s.executables      = ['active_mailbox']

  s.extra_rdoc_files = ['README.markdown', 'LICENSE']
  s.rdoc_options     = ["--charset=UTF-8"]

  s.description = <<-DESC
    ActiveMailbox provides a simple API and command line utility to work
    with voicemail boxes and voicemails generated by Asterisk.
  DESC

end
